SET NAMES utf8mb4;
INSERT INTO nb_card
(card_id,arcana_code,suit_code,rank_code,major_number,title_de,sheet_name,sheet_position,status_code)
VALUES
('major-00','major',NULL,NULL,0,'0 · Der Narr','SheetA-2.png',1,'active'),
('major-01','major',NULL,NULL,1,'I · Der Magier','SheetA-2.png',2,'active'),
('major-02','major',NULL,NULL,2,'II · Die Hohepriesterin','SheetA-2.png',3,'active'),
('major-03','major',NULL,NULL,3,'III · Die Herrscherin','SheetA-2.png',4,'active'),
('major-04','major',NULL,NULL,4,'IV · Der Herrscher','SheetA-2.png',5,'active'),
('major-05','major',NULL,NULL,5,'V · Der Hierophant','SheetA-2.png',6,'active'),
('major-06','major',NULL,NULL,6,'VI · Die Liebenden','SheetB.png',1,'active'),
('major-07','major',NULL,NULL,7,'VII · Der Wagen','SheetB.png',2,'active'),
('major-08','major',NULL,NULL,8,'VIII · Die Kraft','SheetB.png',3,'active'),
('major-09','major',NULL,NULL,9,'IX · Der Eremit','SheetB.png',4,'active'),
('major-10','major',NULL,NULL,10,'X · Das Rad des Schicksals','SheetB.png',5,'active'),
('major-11','major',NULL,NULL,11,'XI · Die Gerechtigkeit','SheetB.png',6,'active'),
('major-12','major',NULL,NULL,12,'XII · Der Gehängte','SheetC.png',1,'active'),
('major-13','major',NULL,NULL,13,'XIII · Der Tod','SheetC.png',2,'active'),
('major-14','major',NULL,NULL,14,'XIV · Die Mäßigkeit','SheetC.png',3,'active'),
('major-15','major',NULL,NULL,15,'XV · Der Teufel','SheetC.png',4,'active'),
('major-16','major',NULL,NULL,16,'XVI · Der Turm','SheetC.png',5,'active'),
('major-17','major',NULL,NULL,17,'XVII · Der Stern','SheetC.png',6,'active'),
('major-18','major',NULL,NULL,18,'XVIII · Der Mond','SheetD.png',1,'active'),
('major-19','major',NULL,NULL,19,'XIX · Die Sonne','SheetD.png',2,'active'),
('major-20','major',NULL,NULL,20,'XX · Das Gericht','SheetD.png',3,'active'),
('major-21','major',NULL,NULL,21,'XXI · Die Welt','SheetD.png',4,'active'),
('wands-ace','minor','wands','ace',NULL,'Ass der Stäbe','SheetE.png',1,'active'),
('wands-02','minor','wands','2',NULL,'Zwei der Stäbe','SheetE.png',2,'active'),
('wands-03','minor','wands','3',NULL,'Drei der Stäbe','SheetE.png',3,'active'),
('wands-04','minor','wands','4',NULL,'Vier der Stäbe','SheetE.png',4,'active'),
('wands-05','minor','wands','5',NULL,'Fünf der Stäbe','SheetE.png',5,'active'),
('wands-06','minor','wands','6',NULL,'Sechs der Stäbe','SheetE.png',6,'active'),
('wands-07','minor','wands','7',NULL,'Sieben der Stäbe','SheetF.png',1,'active'),
('wands-08','minor','wands','8',NULL,'Acht der Stäbe','SheetF.png',2,'active'),
('wands-09','minor','wands','9',NULL,'Neun der Stäbe','SheetF.png',3,'active'),
('wands-10','minor','wands','10',NULL,'Zehn der Stäbe','SheetF.png',4,'active'),
('wands-page','minor','wands','page',NULL,'Bube der Stäbe','SheetG.png',1,'active'),
('wands-knight','minor','wands','knight',NULL,'Ritter der Stäbe','SheetG.png',2,'active'),
('wands-queen','minor','wands','queen',NULL,'Königin der Stäbe','SheetG.png',3,'active'),
('wands-king','minor','wands','king',NULL,'König der Stäbe','SheetG.png',4,'active'),
('cups-ace','minor','cups','ace',NULL,'Ass der Kelche','SheetH.png',1,'active'),
('cups-02','minor','cups','2',NULL,'Zwei der Kelche','SheetH.png',2,'active'),
('cups-03','minor','cups','3',NULL,'Drei der Kelche','SheetH.png',3,'active'),
('cups-04','minor','cups','4',NULL,'Vier der Kelche','SheetH.png',4,'active'),
('cups-05','minor','cups','5',NULL,'Fünf der Kelche','SheetH.png',5,'active'),
('cups-06','minor','cups','6',NULL,'Sechs der Kelche','SheetH.png',6,'active'),
('cups-07','minor','cups','7',NULL,'Sieben der Kelche','SheetI.png',1,'active'),
('cups-08','minor','cups','8',NULL,'Acht der Kelche','SheetI.png',2,'active'),
('cups-09','minor','cups','9',NULL,'Neun der Kelche','SheetI.png',3,'active'),
('cups-10','minor','cups','10',NULL,'Zehn der Kelche','SheetI.png',4,'active'),
('cups-page','minor','cups','page',NULL,'Bube der Kelche','SheetJ.png',1,'active'),
('cups-knight','minor','cups','knight',NULL,'Ritter der Kelche','SheetJ.png',2,'active'),
('cups-queen','minor','cups','queen',NULL,'Königin der Kelche','SheetJ.png',3,'active'),
('cups-king','minor','cups','king',NULL,'König der Kelche','SheetJ.png',4,'active'),
('swords-ace','minor','swords','ace',NULL,'Ass der Schwerter','SheetK.png',1,'active'),
('swords-02','minor','swords','2',NULL,'Zwei der Schwerter','SheetK.png',2,'active'),
('swords-03','minor','swords','3',NULL,'Drei der Schwerter','SheetK.png',3,'active'),
('swords-04','minor','swords','4',NULL,'Vier der Schwerter','SheetK.png',4,'active'),
('swords-05','minor','swords','5',NULL,'Fünf der Schwerter','SheetK.png',5,'active'),
('swords-06','minor','swords','6',NULL,'Sechs der Schwerter','SheetK.png',6,'active'),
('swords-07','minor','swords','7',NULL,'Sieben der Schwerter','SheetL.png',1,'active'),
('swords-08','minor','swords','8',NULL,'Acht der Schwerter','SheetL.png',2,'active'),
('swords-09','minor','swords','9',NULL,'Neun der Schwerter','SheetL.png',3,'active'),
('swords-10','minor','swords','10',NULL,'Zehn der Schwerter','SheetL.png',4,'active'),
('swords-page','minor','swords','page',NULL,'Bube der Schwerter','SheetM.png',1,'active'),
('swords-knight','minor','swords','knight',NULL,'Ritter der Schwerter','SheetM.png',2,'active'),
('swords-queen','minor','swords','queen',NULL,'Königin der Schwerter','SheetM.png',3,'active'),
('swords-king','minor','swords','king',NULL,'König der Schwerter','SheetM.png',4,'active'),
('pentacles-ace','minor','pentacles','ace',NULL,'Ass der Münzen','SheetN.png',1,'active'),
('pentacles-02','minor','pentacles','2',NULL,'Zwei der Münzen','SheetN.png',2,'active'),
('pentacles-03','minor','pentacles','3',NULL,'Drei der Münzen','SheetN.png',3,'active'),
('pentacles-04','minor','pentacles','4',NULL,'Vier der Münzen','SheetN.png',4,'active'),
('pentacles-05','minor','pentacles','5',NULL,'Fünf der Münzen','SheetN.png',5,'active'),
('pentacles-06','minor','pentacles','6',NULL,'Sechs der Münzen','SheetN.png',6,'active'),
('pentacles-07','minor','pentacles','7',NULL,'Sieben der Münzen','SheetO.png',1,'active'),
('pentacles-08','minor','pentacles','8',NULL,'Acht der Münzen','SheetO.png',2,'active'),
('pentacles-09','minor','pentacles','9',NULL,'Neun der Münzen','SheetO.png',3,'active'),
('pentacles-10','minor','pentacles','10',NULL,'Zehn der Münzen','SheetO.png',4,'active'),
('pentacles-page','minor','pentacles','page',NULL,'Bube der Münzen','SheetP.png',1,'active'),
('pentacles-knight','minor','pentacles','knight',NULL,'Ritter der Münzen','SheetP.png',2,'active'),
('pentacles-queen','minor','pentacles','queen',NULL,'Königin der Münzen','SheetP.png',3,'active'),
('pentacles-king','minor','pentacles','king',NULL,'König der Münzen','SheetP.png',4,'active')
ON DUPLICATE KEY UPDATE
 arcana_code=VALUES(arcana_code), suit_code=VALUES(suit_code), rank_code=VALUES(rank_code),
 major_number=VALUES(major_number), title_de=VALUES(title_de), sheet_name=VALUES(sheet_name),
 sheet_position=VALUES(sheet_position), status_code=VALUES(status_code);
