(()=>{"use strict";
const S="nb_kartenraum_frontend_v070",A="../NB_Kartenraum_Backend_v0.6.3/api";let cur=null,depth="SHORT",knowledge=null;
const $=x=>document.getElementById(x), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function st(){try{return JSON.parse(localStorage.getItem(S)||"{}")}catch{return {}}}
function tok(){return st().session_token||""}
async function api(p){let t=tok();if(!t)throw Error("AUTH_REQUIRED");let r=await fetch(`${A}/${p}`,{headers:{Accept:"application/json",Authorization:`Bearer ${t}`}}),d=await r.json().catch(()=>({}));if(!r.ok||d.status!=="ok")throw Error(d.error||d.message||`API_${r.status}`);return d}
function rev(v){return v===true||v===1||v==="1"||["REVERSED","REVERSE","UMGEKEHRT"].includes(String(v||"").toUpperCase())}
function pick(o,...k){for(let x of k)if(o&&o[x]!=null&&String(o[x]).trim())return o[x];return ""}
function renderK(k){knowledge=k;let a=[["Eine Frage",pick(k,"reflection_question","question_text")],["Ein Moment",pick(k,"everyday_moment","moment_text")],["Bedeutung erkunden",pick(k,"meaning_text","meaning")],["Details & Symbolik",pick(k,"symbolism_text","symbolism")],["Andere Blickrichtung",pick(k,"alternative_perspective","other_perspective","reversed_meaning_text")]],n=depth==="SHORT"?2:depth==="MORE"?3:5,items=a.slice(0,n).filter(x=>x[1]);$("drawDetailKnowledge").innerHTML=items.length?items.map(x=>`<article class="draw-knowledge-section"><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join(""):`<p class="draw-detail-empty">Für diese Detailtiefe sind noch keine Informationen hinterlegt.</p>`}
async function loadK(id){$("drawDetailStatus").textContent="Karteninformationen werden geladen …";let aud=st().card_audience_code||st().audience||"ADULT",paths=[`card-knowledge.php?card_id=${encodeURIComponent(id)}&audience_code=${aud}&language_code=de`,`knowledge.php?card_id=${encodeURIComponent(id)}&audience_code=${aud}&language_code=de`],last;for(let p of paths)try{let r=await api(p);renderK(r.knowledge||r.card_knowledge||r.data||r);$("drawDetailStatus").textContent="";return}catch(e){last=e}$("drawDetailStatus").textContent=`Karteninformationen konnten nicht geladen werden${last?.message?": "+last.message:""}.`}
function open(root,img){let d=root?.dataset||{},r=rev(d.reversed||d.isReversed||d.orientation||(root?.classList.contains("reversed")?"REVERSED":""));cur={card_id:d.cardId,thoughts:root?.querySelector("[data-thoughts],.journal-text,.entry-text")?.textContent?.trim()||""};$("drawDetailImage").src=img?.currentSrc||img?.src||"";$("drawDetailImage").classList.toggle("is-reversed",r);$("drawDetailTitle").textContent=d.cardName||root?.querySelector("[data-card-name],h3,h4,strong,b")?.textContent?.trim()||img?.alt||"Deine Karte";$("drawDetailMeta").textContent=d.drawDate||d.date||root?.querySelector("time")?.textContent?.trim()||"";$("drawDetailOrientation").textContent=r?"Umgekehrt gezogen":"Aufrecht gezogen";$("drawDetailJournal").innerHTML=cur.thoughts?`<article class="draw-journal-note"><p>${esc(cur.thoughts)}</p></article>`:`<p class="draw-detail-empty">Zu dieser Ziehung sind hier noch keine Gedanken geladen.</p>`;depth="SHORT";knowledge=null;document.querySelectorAll("[data-depth]").forEach(b=>b.classList.toggle("active",b.dataset.depth===depth));$("drawDetailKnowledge").innerHTML="";let cid=d.cardId||img?.dataset.cardId||root?.closest("[data-card-id]")?.dataset.cardId;if(cid){cur.card_id=cid;loadK(cid)}else $("drawDetailStatus").textContent="Die Karten-ID dieser gespeicherten Ziehung fehlt in der Ansicht.";$("drawDetailViewer").hidden=false;document.body.classList.add("draw-detail-open")}
function close(){$("drawDetailViewer").hidden=true;document.body.classList.remove("draw-detail-open")}
document.addEventListener("click",e=>{if(e.target.closest("[data-draw-detail-close]")){e.preventDefault();close();return}let b=e.target.closest("[data-depth]");if(b){e.preventDefault();depth=b.dataset.depth;document.querySelectorAll("[data-depth]").forEach(x=>x.classList.toggle("active",x===b));if(knowledge)renderK(knowledge);else if(cur?.card_id)loadK(cur.card_id);return}let img=e.target.closest(".journal-card img,.journal-entry img,[data-draw-id] img,.last-encounter img,.last-meeting img,[data-last-draw] img"),tr=e.target.closest("[data-open-draw-detail]");if(!img&&!tr)return;e.preventDefault();e.stopImmediatePropagation();let root=(img||tr).closest("[data-draw-id],[data-card-id],.journal-card,.journal-entry,.last-encounter,.last-meeting,[data-last-draw]");open(root,img||root?.querySelector("img"))},true);
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("drawDetailViewer")?.hidden)close()});
})();